<a href="https://colab.research.google.com/github/AlexisG81/etl-data-pipeline/blob/main/Notebooks/Aseguradora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

In [7]:
df = pd.read_csv(url)

In [8]:
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [9]:
df.shape

df.columns

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [11]:
def limpiar_dataframe(df):



    df.columns = df.columns.str.strip().str.lower()



    for col in df.select_dtypes(include='object').columns:

        df[col] = df[col].astype(str).str.strip()



    df = df.replace(r'^\s*$', pd.NA, regex=True)



    df = df.drop_duplicates()



    return df

In [13]:
df['rating_riesgo'] = df['rating_riesgo'].replace({
    'B': 'Bajo',
    'D': 'Bajo'
})

In [14]:
df['rating_riesgo'] = df['rating_riesgo'].fillna('Sin clasificación')

In [15]:
df['pais'] = df['pais'].replace({
    'ElSalvador': 'El Salvador'
})

In [20]:
df.head(15)

    id_aseguradora          nombre                 pais      rating_riesgo
0                1   Aseguradora 1           Costa Rica               Alto
1                2   Aseguradora 2          El Salvador               Bajo
2                3   Aseguradora 3          El Salvador  Sin clasificación
3                4   Aseguradora 4           Costa Rica              Medio
4                5   Aseguradora 5          El Salvador               Bajo
5                6   Aseguradora 6  Sin pais Registrado              Medio
6                7   Aseguradora 7            Guatemala               Alto
7                8   Aseguradora 8               Panamá               Bajo
8                9   Aseguradora 9  Sin pais Registrado               Bajo
9               10  Aseguradora 10               Panamá  Sin clasificación
10              11  Aseguradora 11             Honduras               Bajo
11              12  Aseguradora 12          El Salvador               Bajo
12              13  Aseguradora 13             Honduras               Alto
13              14  Aseguradora 14          El Salvador  Sin clasificación
14              15  Aseguradora 15          El Salvador               Alto

In [19]:
df['pais'] = df['pais'].fillna('Sin pais Registrado')

In [21]:
df = df.drop_duplicates()

In [22]:
df.columns = df.columns.str.strip().str.lower()

for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

In [23]:
df.head(15)

    id_aseguradora          nombre                 pais      rating_riesgo
0                1   Aseguradora 1           Costa Rica               Alto
1                2   Aseguradora 2          El Salvador               Bajo
2                3   Aseguradora 3          El Salvador  Sin clasificación
3                4   Aseguradora 4           Costa Rica              Medio
4                5   Aseguradora 5          El Salvador               Bajo
5                6   Aseguradora 6  Sin pais Registrado              Medio
6                7   Aseguradora 7            Guatemala               Alto
7                8   Aseguradora 8               Panamá               Bajo
8                9   Aseguradora 9  Sin pais Registrado               Bajo
9               10  Aseguradora 10               Panamá  Sin clasificación
10              11  Aseguradora 11             Honduras               Bajo
11              12  Aseguradora 12          El Salvador               Bajo
12              13  Aseguradora 13             Honduras               Alto
13              14  Aseguradora 14          El Salvador  Sin clasificación
14              15  Aseguradora 15          El Salvador               Alto