Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

Cargar Dataset

In [38]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

siniestros = pd.read_csv(url)

Exploración de datos

In [39]:
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [40]:
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

In [41]:
siniestros.isnull().sum()

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [42]:
siniestros.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [43]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [44]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [45]:
siniestros = normalizar_columnas(siniestros)
siniestros = limpiar_texto(siniestros)
siniestros = siniestros.drop_duplicates()

Funciones especificas

In [66]:
#Cambiar formato de estado
map_estado = {
"ABIERTO": "Abierto",
"Rechazado": "Cerrado",
"RECHAZADO" : "Cerrado"
}

siniestros ["estado"] = (
    siniestros["estado"]

    .replace(map_estado)
)
#Convertir fecha en datetime
siniestros["fecha_siniestro"] = pd.to_datetime(
    siniestros["fecha_siniestro"],
    errors="coerce",
    dayfirst=True,
    infer_datetime_format=True
)

#convertir monto en entero
siniestros["monto_siniestro"] = (
    siniestros["monto_siniestro"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

siniestros["monto_siniestro"] = pd.to_numeric(siniestros["monto_siniestro"], errors="coerce")

/tmp/ipykernel_15003/3663925634.py:14: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  siniestros["fecha_siniestro"] = pd.to_datetime(

In [67]:
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  918 non-null    datetime64[ns]
 3   monto_siniestro  3677 non-null   float64
 4   estado           3322 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 180.6+ KB

In [68]:
siniestros.head()

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro   estado
0             1      17400      2025-10-16          2092.59  Abierto
1             2       2465             NaT          7076.25  Abierto
2             3      15785      2025-09-19           702.27  cerrado
3             4      14299             NaT           274.63  Abierto
4             5      12908             NaT          9377.69  Cerrado

Separar validos y rechazados

In [69]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null

columnas_obligatorias = [
    "id_siniestro",
    "id_poliza",
    "fecha_siniestro",
    "monto_siniestro",
    "estado"
]

validos = siniestros [
 siniestros[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = siniestros [
 siniestros[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados_negativos= siniestros[
    (siniestros["monto_siniestro"] < 0)
].copy()

Motivo del rechazo

In [70]:
def motivo(row):
    motivos = []

    if pd.isna(row["id_siniestro"]):
        motivos.append("id_siniestro_nulo")

    if pd.isna(row["id_poliza"]):
        motivos.append("id_poliza_nulo")

    if pd.isna(row["fecha_siniestro"]):
        motivos.append("fecha_siniestro_nulo")

    if pd.isna(row["monto_siniestro"]) or row["monto_siniestro"] < 0:
        motivos.append("monto_siniestro_invalido")

    if pd.isna(row["estado"]):
        motivos.append("estado_nulo")

    return ", ".join(motivos)

Agregar motivo de rechazo

Exportar Archivos

In [71]:
validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [72]:
validos.head()

    id_siniestro  id_poliza fecha_siniestro  monto_siniestro   estado
0              1      17400      2025-10-16          2092.59  Abierto
2              3      15785      2025-09-19           702.27  cerrado
7              8      23824      2025-01-17          2736.20  Abierto
12            13       3716      2025-07-13         -4274.39  Cerrado
23            24      17180      2025-06-13          6183.83  cerrado

In [73]:
validos.dtypes

id_siniestro                int64
id_poliza                   int64
fecha_siniestro    datetime64[ns]
monto_siniestro           float64
estado                     object
dtype: object

In [74]:
validos.isnull().sum()

id_siniestro       0
id_poliza          0
fecha_siniestro    0
monto_siniestro    0
estado             0
dtype: int64

In [75]:
validos.value_counts()

id_siniestro  id_poliza  fecha_siniestro  monto_siniestro  estado
4620          10815      2025-10-11        14958.46000     Abierto    1
1             17400      2025-10-16        2092.59000      Abierto    1
3             15785      2025-09-19        702.27000       cerrado    1
8             23824      2025-01-17        2736.20000      Abierto    1
13            3716       2025-07-13       -4274.39000      Cerrado    1
                                                                     ..
93            1928       2025-01-31        12706.47000     Abierto    1
67            5049       2025-05-26        13.72301        Cerrado    1
66            14064      2025-03-25        9842.05000      Abierto    1
45            15100      2025-01-27        8761.24000      Abierto    1
36            16929      2025-01-06        3649.94000      cerrado    1
Name: count, Length: 534, dtype: int64

In [76]:
validos.to_sql(
    "siniestros",
    engine,
    if_exists="append",
    index=False
  )

534

Validar Carga

In [77]:
pd.read_sql(
    "Select * From siniestros Limit 100",
    engine
)

    id_siniestro  id_poliza fecha_siniestro  monto_siniestro   estado
0              1      17400      2025-10-16       2092.59000  Abierto
1              3      15785      2025-09-19        702.27000  cerrado
2              8      23824      2025-01-17       2736.20000  Abierto
3             13       3716      2025-07-13      -4274.39000  Cerrado
4             24      17180      2025-06-13       6183.83000  cerrado
..           ...        ...             ...              ...      ...
95           881       1160      2025-02-13      14837.14000  cerrado
96           883       8904      2025-04-27          6.13342  Cerrado
97           895      19216      2026-01-14       7478.23000  Abierto
98           901       9443      2025-04-08          9.97345  Cerrado
99           916      21501      2025-11-06         13.52730  Abierto

[100 rows x 5 columns]