Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 21.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

Cargar Dataset

In [4]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

tipos_seguro = pd.read_csv(url)

Exploración de datos

In [5]:
tipos_seguro.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [6]:
tipos_seguro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

In [7]:
tipos_seguro.isnull().sum()

id_tipo_seguro    0
tipo              0
categoria         2
riesgo_base       2
dtype: int64

In [8]:
tipos_seguro.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [9]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [10]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [11]:
tipos_seguro = normalizar_columnas(tipos_seguro)
tipos_seguro = limpiar_texto(tipos_seguro)
tipos_seguro = tipos_seguro.drop_duplicates()

Funciones especificas

In [12]:
tipos_seguro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

In [13]:
tipos_seguro.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

Separar validos y rechazados

In [14]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null

columnas_obligatorias = [
    "id_tipo_seguro",
    "tipo",
    "categoria",
    "riesgo_base"
]

validos = tipos_seguro [
 tipos_seguro[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = tipos_seguro [
 tipos_seguro[columnas_obligatorias].notna().all(axis=1)
].copy()

Motivo del rechazo

In [15]:
def motivo(row):
    motivos = []

    if pd.isna(row["id_tipo_seguro"]):
        motivos.append("id_tipo_seguro_nulo")

    if pd.isna(row["tipo"]):
        motivos.append("tipo_nulo")

    if pd.isna(row["categoria"]):
        motivos.append("categoria_es_nulo")

    if pd.isna(row["riesgo_base"]):
        motivos.append("riesgo_base_nulo")

    return ", ".join(motivos)

Agregar motivo de rechazo

Exportar Archivos

In [16]:
validos.to_csv("tipos_seguro_curated.csv", index=False)
rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [17]:
validos.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
4               5        Auto  empresarial         9.07
5               6  Industrial   Empresarial        2.52

In [18]:
validos.dtypes

id_tipo_seguro     int64
tipo              object
categoria         object
riesgo_base       object
dtype: object

In [19]:
validos.isnull().sum()

id_tipo_seguro    0
tipo              0
categoria         0
riesgo_base       0
dtype: int64

In [20]:
validos.value_counts()

id_tipo_seguro  tipo        categoria     riesgo_base
1               Pyme        Familiar      -              1
2               Industrial  Empresarial    4.68          1
3               Industrial  Familiar      5.10           1
5               Auto        empresarial   9.07           1
6               Industrial  Empresarial   2.52           1
7               Salud       Personal       0.92          1
8               Educación   empresarial    7.42          1
10              Dental      Especial      2.70           1
11              Auto        empresarial   4.33           1
Name: count, dtype: int64

In [21]:
validos.to_sql(
    "tipos_seguro",
    engine,
    if_exists="append",
    index=False
  )

9

Validar Carga

In [22]:
pd.read_sql(
    "Select * From tipos_seguro Limit 100",
    engine
)

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               5        Auto  empresarial         9.07
4               6  Industrial   Empresarial        2.52
5               7       Salud      Personal       0.92
6               8   Educación  empresarial        7.42
7              10      Dental      Especial        2.70
8              11        Auto  empresarial         4.33