Importar Librerias

In [1]:
import pandas as pd
import numpy as np

Conexion a PostgreSQL

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 21.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

Cargar Dataset

In [25]:
#En esta url va el RAW de nuestro csv subido en github
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"

clientes = pd.read_csv(url)

Exploración de datos

In [26]:
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [27]:
clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            2435 non-null   object
 4   fecha_nacimiento  3030 non-null   object
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: int64(1), object(6)
memory usage: 165.8+ KB

In [28]:
clientes.isnull().sum()

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [29]:
clientes.duplicated().sum()

np.int64(0)

Funciones reutilizables

In [30]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [31]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

Aplicar Limpieza

In [32]:
clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes = clientes.drop_duplicates()

Funciones especificas

In [45]:
import pandas as pd

# cambiar fecha a datetime
clientes["fecha_nacimiento"] = pd.to_datetime(
    clientes["fecha_nacimiento"].astype(str).str.strip(),
    errors="coerce"
)

# Asignación de género
map_genero = {
    "m": "Masculino",
    "M": "Masculino",
    "masculino": "Masculino",
    "male": "Masculino",

    "f": "Femenino",
    "F": "Femenino",
    "fem": "Femenino",
    "femenino": "Femenino",
    "female": "Femenino"
}

clientes["genero"] = clientes["genero"].map(map_genero)

nombres_masculinos = {
    "juan", "carlos", "jose", "luis", "miguel", "andres",
    "alex", "daniel", "fernando", "ricardo", "manuel"
}

nombres_femeninos = {
    "maria", "ana", "sofia", "laura", "carmen", "elena",
    "luisa", "valeria", "gabriela", "patricia"
}

def inferir_genero(row):
    if pd.isna(row["genero"]):
        nombre = str(row["nombre"]).split()[0].lower()

        if nombre in nombres_masculinos:
            return "Masculino"
        elif nombre in nombres_femeninos:
            return "Femenino"

    return row["genero"]

clientes["genero"] = clientes.apply(inferir_genero, axis=1)

#modificacion de ciudades

map_ciudades = {
    "SanMiguel" : "San Miguel",
    "Sta. Ana" : "Santa Ana",
    "S. Miguel" : "San Miguel",
    "LaLibertad" : "La Libertad",
    "SantaAna" : "Santa Ana",
    "Sonso" : "Sonsonate",
    "SS" : "San Salvador"
    }

clientes["ciudad"] = (
    clientes["ciudad"]

    .replace(map_ciudades)
)

#Configuracion del segmento

map_segmento = {
    "REGULAR" : "Regular",
    "Pyme" : "Pyme",
    "PYME" : "Pyme",
    "PREMIUM" : "Premium",
    "VIP" : "Vip"
}

clientes["segmento"] = (
    clientes["segmento"]

    .replace(map_segmento)
)

In [46]:
clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3030 entries, 0 to 3029
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        3030 non-null   int64
 1   nombre            3030 non-null   object
 2   email             3030 non-null   object
 3   genero            1083 non-null   object
 4   fecha_nacimiento  585 non-null    datetime64[ns]
 5   ciudad            3030 non-null   object
 6   segmento          2433 non-null   object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 165.8+ KB

In [47]:
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,NaN,2011-11-24,San Miguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,NaT,Santa Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,NaT,San Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,NaN,NaT,La Libertad,Regular
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945-08-02,San Salvador,Pyme

Separar validos y rechazados

In [49]:
#Primero debemos colocar que reglas queremos tener para poder separarlos entra validos y rechazados
#Reglas
#1. El id debe ser not null
#2. El nombre no puede estar vacio

columnas_obligatorias = [
    "id_cliente",
    "nombre",
    "email",
    "genero",
    "fecha_nacimiento",
    "ciudad",
    "segmento"
]

validos = clientes [
 clientes[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = clientes [
 clientes[columnas_obligatorias].notna().all(axis=1)
].copy()

Motivo del rechazo

In [51]:
def motivo(row):
    motivos = []

    if pd.isna(row["id_cliente"]):
        motivos.append("id_tipo_cliente_nulo")

    if pd.isna(row["nombre"]):
        motivos.append("nombre_nulo")

    if pd.isna(row["email"]):
        motivos.append("email_es_nulo")

    if pd.isna(row["genero"]):
        motivos.append("genero_es_nulo")

    if pd.isna(row["fecha_nacimiento"]):
        motivos.append("fecha_nacimiento_es_nulo")

    if pd.isna(row["ciudad"]):
        motivos.append("ciudad_es_nula")

    if pd.isna(row["segmento"]):
        motivos.append("segmento_es_nulo")

    return ", ".join(motivos)

Agregar motivo de rechazo

Exportar Archivos

In [52]:
validos.to_csv("clientes_curated.csv", index=False)
rechazados.to_csv("clientes_rejects.csv", index=False)

Cargar datos en PostgreSQL

Para evitar errores de carga y mostrar los detalles

In [53]:
validos.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
5,6,Ricardo López Vásquez,ricardo.lopez.vasquez6@seguro.sv,Masculino,1966-10-15,sonsonate,Pyme
12,13,Carlos Santos Morales,carlos.santos.morales6@correo.com,Masculino,1975-08-02,Santa Ana,Regular
18,19,Ana Mendoza Ramírez,ana.mendoza.ramirez5@seguro.sv,Femenino,1947-09-06,Santa Ana,Pyme
32,33,Ricardo Chávez García,ricardo.chavez.garcia5@seguro.sv,Masculino,1993-08-26,San Miguel,vip
54,55,Ana Santos Martínez,ana.santos.martinez6@example.com,Femenino,1994-05-27,san miguel,Premium

In [54]:
validos.dtypes

id_cliente                   int64
nombre                      object
email                       object
genero                      object
fecha_nacimiento    datetime64[ns]
ciudad                      object
segmento                    object
dtype: object

In [55]:
validos.isnull().sum()

id_cliente          0
nombre              0
email               0
genero              0
fecha_nacimiento    0
ciudad              0
segmento            0
dtype: int64

In [56]:
validos.value_counts()

id_cliente  nombre                        email                               genero     fecha_nacimiento  ciudad          segmento
6           Ricardo López Vásquez         ricardo.lopez.vasquez6@seguro.sv    Masculino  1966-10-15        sonsonate       Pyme        1
13          Carlos Santos Morales         carlos.santos.morales6@correo.com   Masculino  1975-08-02        Santa Ana       Regular     1
19          Ana Mendoza Ramírez           ana.mendoza.ramirez5@seguro.sv      Femenino   1947-09-06        Santa Ana       Pyme        1
33          Ricardo Chávez García         ricardo.chavez.garcia5@seguro.sv    Masculino  1993-08-26        San Miguel      vip         1
55          Ana Santos Martínez           ana.santos.martinez6@example.com    Femenino   1994-05-27        san miguel      Premium     1
                                                                                                                                      ..
2973        Luis Morales Aguilar          luis.morales.aguilar5@gmail.com     Masculino  1946-10-09         San Salvador   Pyme        1
2977        Ricardo Santos Reyes          ricardo.santos.reyes2@mail.com      Masculino  1985-05-08        San Miguel      vip         1
2984        Carlos Cruz Mendoza           carlos.cruz.mendoza2@correo.com     Masculino  2000-09-04        San salvador    Regular     1
3017        Carmen Ramírez Vásquez (dup)  carmen.ramirez.vasquez3@correo.com  Femenino   1999-01-10        L. Libertad     Regular     1
3024        Valeria Santos Mendoza (dup)  valeria.santos.mendoza5@correo.com  Femenino   1984-04-26         Sonsonate      Premium     1
Name: count, Length: 163, dtype: int64

In [57]:
validos.to_sql(
    "clientes",
    engine,
    if_exists="append",
    index=False
  )

163

Validar Carga

In [58]:
pd.read_sql(
    "Select * From clientes Limit 100",
    engine
)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Masculino,2011/11/24,SanMiguel,None
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,nan,01-02-80,Santa Ana,None
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,San Miguel,None
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,La Libertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,nan,1945/08/02,San Salvador,Pyme
...,...,...,...,...,...,...,...
95,96,Daniela Pérez Martínez,daniela.perez.martinez5@example.com,Masculino,1980/06/01,Santa Ana,PREMIUM
96,97,Paula Chávez Mendoza,paula.chavez.mendoza6@example.com,femenino,11-24-86,La Libertad,REGULAR
97,98,Karla Martínez Reyes,karla.martinez.reyes0@gmail.com,Masculino,29-11-1945,San Miguel,None
98,99,Luis Reyes García,luis.reyes.garcia1@example.com,Femenino,12-04-1992,Santa Ana,vip
99,100,Carlos Ortiz Morales,carlos.ortiz.morales2@correo.com,Masculino,1997/09/23,San Salvador,None